"""extend student profile

Revision ID: 1756dd775441
Revises: 42149776437b
Create Date: 2026-09-11 20:36:43.618494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1756dd775441'
down_revision: Union[str, None] = '42149776437b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('personal_email', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('profile_photo_id', sa.UUID(), nullable=True))
    op.add_column('student_profiles', sa.Column('degree', sa.String(), nullable=False, server_default='B.Tech'))
    op.add_column('student_profiles', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('admission_year', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('current_year', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('current_semester', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('tenth_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('student_profiles', sa.Column('tenth_board', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('twelfth_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('student_profiles', sa.Column('twelfth_board', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('diploma_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('student_profiles', sa.Column('history_of_backlogs', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('student_profiles', sa.Column('year_gaps', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'student_profiles', 'stored_files', ['profile_photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'year_gaps')
    op.drop_column('student_profiles', 'history_of_backlogs')
    op.drop_column('student_profiles', 'diploma_percentage')
    op.drop_column('student_profiles', 'twelfth_board')
    op.drop_column('student_profiles', 'twelfth_percentage')
    op.drop_column('student_profiles', 'tenth_board')
    op.drop_column('student_profiles', 'tenth_percentage')
    op.drop_column('student_profiles', 'current_semester')
    op.drop_column('student_profiles', 'current_year')
    op.drop_column('student_profiles', 'admission_year')
    op.drop_column('student_profiles', 'specialization')
    op.drop_column('student_profiles', 'degree')
    op.drop_column('student_profiles', 'profile_photo_id')
    op.drop_column('student_profiles', 'phone_number')
    op.drop_column('student_profiles', 'personal_email')
    # ### end Alembic commands ###