"""tnpc domain expansion

Revision ID: 42149776437b
Revises: aaaa706ceec2
Create Date: 2026-09-11 12:04:16.172825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '42149776437b'
down_revision: Union[str, None] = 'aaaa706ceec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('result_status', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuing_organization', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stored_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('active_backlogs', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('headquarters', sa.String(), nullable=True),
    sa.Column('logo_file_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logo_file_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('drive_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registration_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drive_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drive_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('application_limit', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ctc_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('stipend_monthly', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('application_deadline', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('announcement_type', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('contact_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_document_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('stored_file_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_eligible_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'graduation_year', name='uq_drive_batch')
    )
    op.create_table('drive_eligible_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'branch_id', name='uq_drive_branch')
    )
    op.create_table('drive_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('one_job_per_student', sa.Boolean(), nullable=False),
    sa.Column('one_company_per_student', sa.Boolean(), nullable=False),
    sa.Column('allow_students_with_existing_offers', sa.Boolean(), nullable=False),
    sa.Column('allow_withdrawal', sa.Boolean(), nullable=False),
    sa.Column('require_consent', sa.Boolean(), nullable=False),
    sa.Column('placement_policy', sa.Text(), nullable=True),
    sa.Column('eligibility_policy', sa.Text(), nullable=True),
    sa.Column('withdrawal_policy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id')
    )
    op.create_table('drive_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('eliminatory', sa.Boolean(), nullable=False),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('minimum_cgpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('maximum_cgpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('minimum_10th_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_12th_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_diploma_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passing_year_from', sa.Integer(), nullable=True),
    sa.Column('passing_year_to', sa.Integer(), nullable=True),
    sa.Column('backlogs_allowed', sa.Boolean(), nullable=False),
    sa.Column('maximum_backlogs', sa.Integer(), nullable=True),
    sa.Column('active_backlogs_allowed', sa.Boolean(), nullable=False),
    sa.Column('education_gap_allowed', sa.Boolean(), nullable=False),
    sa.Column('maximum_education_gap_years', sa.Integer(), nullable=True),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_age', sa.Integer(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id')
    )
    op.create_table('job_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=True),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eligibility_checked', sa.Boolean(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('eligibility_reason', sa.Text(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'student_id', 'job_position_id', name='uq_application'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('assessment_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('coding_questions', sa.Integer(), nullable=True),
    sa.Column('mcq_questions', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('assessment_platform', sa.String(), nullable=True),
    sa.Column('assessment_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['drive_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id')
    )
    op.create_table('compensations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('annual_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fixed_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variable_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_stipend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('joining_bonus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retention_bonus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_position_id')
    )
    op.create_table('education_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=True),
    sa.Column('job_position_id', sa.UUID(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.Column('minimum_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_cgpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('minimum_months', sa.Integer(), nullable=True),
    sa.Column('maximum_months', sa.Integer(), nullable=True),
    sa.Column('freshers_allowed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_position_id')
    )
    op.create_table('internship_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('stipend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('ppo_available', sa.Boolean(), nullable=False),
    sa.Column('ppo_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_position_id')
    )
    op.create_table('job_certification_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_position_id', 'certification_id', name='uq_jp_cert')
    )
    op.create_table('job_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_position_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('skill_level', sa.String(), nullable=True),
    sa.Column('minimum_experience_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_position_id', 'skill_id', name='uq_jp_skill')
    )
    op.create_table('application_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('stored_file_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drive_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('drive_shortlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('shortlist_type', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('shortlisted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['shortlisted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('evaluated_by', sa.UUID(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['drive_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'round_id', name='uq_app_round')
    )
    op.create_table('drive_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('offered_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('offered_stipend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('offer_status', sa.String(), nullable=False),
    sa.Column('offer_letter_file_id', sa.UUID(), nullable=True),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['offer_letter_file_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['selection_id'], ['drive_selections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_id')
    )
    op.create_table('placement_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('selection_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('package_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.ForeignKeyConstraint(['selection_id'], ['drive_selections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_outcomes')
    op.drop_table('drive_offers')
    op.drop_table('round_results')
    op.drop_table('drive_shortlists')
    op.drop_table('drive_selections')
    op.drop_table('application_status_history')
    op.drop_table('application_documents')
    op.drop_table('job_position_skills')
    op.drop_table('job_locations')
    op.drop_table('job_certification_requirements')
    op.drop_table('internship_details')
    op.drop_table('experience_requirements')
    op.drop_table('education_requirements')
    op.drop_table('compensations')
    op.drop_table('assessment_configurations')
    op.drop_table('applications')
    op.drop_table('job_positions')
    op.drop_table('eligibility_criteria')
    op.drop_table('drive_schedules')
    op.drop_table('drive_rounds')
    op.drop_table('drive_policies')
    op.drop_table('drive_eligible_branches')
    op.drop_table('drive_eligible_batches')
    op.drop_table('drive_documents')
    op.drop_table('drive_document_requirements')
    op.drop_table('drive_contacts')
    op.drop_table('drive_announcements')
    op.drop_table('drives')
    op.drop_table('companies')
    op.drop_table('student_profiles')
    op.drop_table('stored_files')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('certifications')
    op.drop_table('branches')
    op.drop_table('audit_log')
    # ### end Alembic commands ###